#############################################################################
# Generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#  Jun 20, 2020 12:04:21 PM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background #d5d9dd 
    wm focusmodel $top passive
    wm geometry $top 580x525+587+361
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "FreqMods GUI (Filippo Valmori)"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text RUN 
    vTcl:DefineAlias "$top.but44" "Button_RUN" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text FSK -variable che45 
    vTcl:DefineAlias "$top.che45" "Checkbutton_FSK" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text CPFSK -variable che46 
    vTcl:DefineAlias "$top.che46" "Checkbutton_CPFSK" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m48
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe49 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe49" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes50 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text PARAMETERS -width 80 
    vTcl:DefineAlias "$top.mes50" "Message_Par" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent52" "Entry_Rb" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent54" "Entry_M" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes56 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Oversampling
factor [Sa/S]} -width 82 
    vTcl:DefineAlias "$top.mes56" "Message_osf" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes57 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Modulation order} -width 100 
    vTcl:DefineAlias "$top.mes57" "Message_M" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent58" "Entry_h" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab59 \
        -font TkDefaultFont -foreground black -text MESSAGES \
        -background $vTcl(actual_gui_bg) -height 275 -width 230 
    vTcl:DefineAlias "$top.lab59" "Labelframe_OutPrint" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes60 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Number of bits} -width 88 
    vTcl:DefineAlias "$top.mes60" "Message_Nbits" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent61 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent61" "Entry_Nbits" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes62 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Modulation index} -width 100 
    vTcl:DefineAlias "$top.mes62" "Message_h" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent63" "Entry_osf" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes64 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Gaussian
filter span [S]} -width 71 
    vTcl:DefineAlias "$top.mes64" "Message_span" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent65 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent65" "Entry_span" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes66 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Gaussian
filter sps [Sa/S]} -width 80 
    vTcl:DefineAlias "$top.mes66" "Message_sps" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes67 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Gaussian filter
BT factor} -width 80 
    vTcl:DefineAlias "$top.mes67" "Message_BT" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes68 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {SDR sample
rate [Sa/s]} -width 70 
    vTcl:DefineAlias "$top.mes68" "Message_FsSDR" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes69 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Bit rate [b/s]} -width 70 
    vTcl:DefineAlias "$top.mes69" "Message_Rb" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent70 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent70" "Entry_sps" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent71 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent71" "Entry_BT" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent72 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent72" "Entry_FsSDR" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text GFSK -variable che73 
    vTcl:DefineAlias "$top.che73" "Checkbutton_GFSK" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {SDR BIN} -variable che74 
    vTcl:DefineAlias "$top.che74" "Checkbutton_SDR" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but44 \
        -in $top -x 380 -y 60 -width 67 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che45 \
        -in $top -x 40 -y 430 -width 61 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che46 \
        -in $top -x 130 -y 430 -height 25 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $top.tSe49 \
        -in $top -x 270 -y 40 -height 0 -relheight 0.865 -anchor nw \
        -bordermode inside 
    place $top.mes50 \
        -in $top -x 80 -y 30 -width 80 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 150 -y 110 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 150 -y 140 -anchor nw -bordermode ignore 
    place $top.mes56 \
        -in $top -x 20 -y 200 -width 82 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes57 \
        -in $top -x 20 -y 140 -width 100 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 150 -y 170 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 310 -y 160 -width 230 -relwidth 0 -height 275 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes60 \
        -in $top -x 20 -y 80 -width 88 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent61 \
        -in $top -x 150 -y 80 -anchor nw -bordermode ignore 
    place $top.mes62 \
        -in $top -x 20 -y 170 -width 100 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 150 -y 210 -anchor nw -bordermode ignore 
    place $top.mes64 \
        -in $top -x 20 -y 240 -width 71 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 150 -y 250 -anchor nw -bordermode ignore 
    place $top.mes66 \
        -in $top -x 20 -y 280 -width 80 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes67 \
        -in $top -x 20 -y 320 -width 80 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes68 \
        -in $top -x 20 -y 360 -width 70 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes69 \
        -in $top -x 20 -y 110 -width 70 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent70 \
        -in $top -x 150 -y 290 -anchor nw -bordermode ignore 
    place $top.ent71 \
        -in $top -x 150 -y 330 -anchor nw -bordermode ignore 
    place $top.ent72 \
        -in $top -x 150 -y 370 -anchor nw -bordermode ignore 
    place $top.che73 \
        -in $top -x 50 -y 470 -width 55 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che74 \
        -in $top -x 130 -y 470 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

